const list = [
    {
      id: 1,
      title: "VEEP",
      author: "by Armando Iannucci",
      price: 600,
      img: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/51IDj4Q8zZL.jpg",
      amount: 1,
    },
    {
      id: 2,
      title: "MALCOM IN THE MIDDLE",
      author: "by Linwood Boomer",
      price: 700,
      img: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/511+ikgmhNL.jpg",
      amount: 1,
    },
    {
      id: 3,
      title: "DEXTER",
      author: "by 	James Manos Jr.",
      price: 1000,
      img: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/71ivk-MCtDL._SY741_.jpg",
      amount: 1,
    },
    {
      id: 4,
      title: "GAME OF THRONES",
      author: "by  David Benioff, George R. R. Martin, D. B. Weiss",
      price: 900,
      img: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/61o6pfHHU-L._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
      amount: 1,
    },
    {
      id: 5,
      title: "BROOKLYN NINE NINE",
      author: "by by Michael Schur, Dan Goor",
      price: 800,
      img: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/614d6C3G7SL._SX198_BO1,204,203,200_QL40_FMwebp_.jpg",
      amount: 1,
    },
    {
      id: 6,
      title: "PRISON BREAK",
      author: "by Paul Scheuring",
      price: 950,
      img: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/91fbwB3JPzL._SY741_.jpg",
      amount: 1,
    },
    {
      id: 7,
      title: "PSYCH ",
      author: "by Steve Franks",
      price: 750,
      img: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/81oAciB1QVL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 8,
      title: "MODERN FAMILY",
      author: "by Christopher Lloyd, Steven Levitan ",
      price: 790,
      img: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/915LhrnNhGL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 9,
      title: "IT'S SUNNY IN PHILADELPHIA ",
      author: " by Charlie Day, Rob McElhenney, Glenn Howerton",
      price: 800,
      img: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/71t+8aG+VlL._AC_UL480_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 10,
      title: "BIG BANG THEORY",
      author: "by Chuck Lorre, Bill Prady",
      price: 850,
      img: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/81vbMSWDqvL._AC_UL480_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 11,
      title: "FRIENDS",
      author: "by Marta Kauffman, David Crane, Dana Klein,  ",
      price: 750,
      img: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/7103aePOXVL._AC_UL480_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 12,
      title: "THE OFFICE",
      author: "by Greg Daniels, Michael Schur ",
      price: 850,
      img: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/91EAFi+ympL._AC_UL480_FMwebp_QL65_.jpg",
      amount: 1,
    },
];

export default list;